os: osx

osx_image: xcode8.3

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - BINTRAY_ROOT_URL="https://dl.bintray.com/pinepain/bottles-devtools"
      BINTRAY_USER=pinepain

before_install:
 - env
 - xcodebuild -version
 - export TARGET_FORMULA=`echo ${TRAVIS_COMMIT_MESSAGE} | perl -n -e'/^build\s+([a-z0-9-@.]+)$/ && print $1'`
 - export TARGET_FORMULA_NAME=`echo $TARGET_FORMULA | tr @ :`
 - env
 - if [ ! -f "./Formula/${TARGET_FORMULA}.rb" ]; then echo "Target formula \"${TARGET_FORMULA}\" does not exists"; exit 1; fi
 - git remote add upstream "https://$GH_TOKEN@github.com/${TRAVIS_REPO_SLUG}.git"
 - git config --global user.name "Travis CI"
 - git config --global user.email "travis@travis-ci.org"
 - unset TRAVIS
 - brew tap homebrew/php
 - brew tap pinepain/devtools .

install: skip

script:
  - brew fetch --retry  --build-bottle ./Formula/${TARGET_FORMULA}.rb
  - brew install --only-dependencies --build-bottle ./Formula/${TARGET_FORMULA}.rb
  - brew install --verbose --build-bottle ./Formula/${TARGET_FORMULA}.rb
  - brew audit --online ./Formula/${TARGET_FORMULA}.rb || true
  - brew bottle --json --root-url="${BINTRAY_ROOT_URL}" --force-core-tap ./Formula/${TARGET_FORMULA}.rb

after_success:
  - ls -la
  - export FORMULA_JSON=`ls | grep $TARGET_FORMULA | grep json`
  - export FORMULA_BOTTLE=`ls | grep $TARGET_FORMULA | grep tar.gz`
  - export FORMULA_VERSION=`echo ${FORMULA_JSON} | sed 's/.*-\([0-9\.][_0-9\.]*\)\..*/\1/'`
  - env
  - brew bottle --merge --write --no-commit --root-url="${BINTRAY_ROOT_URL}" $FORMULA_JSON
  - git status
  - git checkout ${TRAVIS_BRANCH}
  - git commit -m "Build and deploy ${TARGET_FORMULA} source package [skip ci]" ./Formula
  - git pull --rebase origin ${TRAVIS_BRANCH}
  - git push upstream HEAD:${TRAVIS_BRANCH}
  - curl -T ${FORMULA_BOTTLE} -u${BINTRAY_USER}:${BINTRAY_API_KEY} https://api.bintray.com/content/pinepain/bottles-devtools/${TARGET_FORMULA_NAME}/${FORMULA_VERSION}/${FORMULA_BOTTLE}
  - curl -X POST -u${BINTRAY_USER}:${BINTRAY_API_KEY} https://api.bintray.com/content/pinepain/bottles-devtools/${TARGET_FORMULA_NAME}/${FORMULA_VERSION}/publish
